// Types for workout tracking feature

import { i18n } from '../lib/i18n';

export type BodyRegion = 'upper' | 'lower' | 'core';

export type MuscleGroup =
  | 'chest' | 'back' | 'shoulders' | 'arms'                  // upper
  | 'legs' | 'quads' | 'hamstrings' | 'glutes' | 'adductors' | 'calves'    // lower
  | 'abs' | 'obliques';                                       // core

export type MovementType = 'compound' | 'isolation';

/**
 * Training emphasis of an exercise.
 * - 'strength'    = resistance / weightlifting work, including isometric holds (plank, levers).
 * - 'endurance'   = steady-state cardio / locomotion (running, cycling, rowing, swimming, jump rope).
 * - 'conditioning'= higher-intensity metabolic work (burpees, mountain climbers, battle rope, sled push).
 * - 'mobility'    = flexibility / range-of-motion work (stretches, dynamic mobility drills, foam rolling).
 * - 'power'       = explosive / ballistic work (Olympic lifts, jumps & plyometrics, throws, sprints).
 * Defaults to 'strength' when omitted. For the strength-vs-cardio focus split, `power` counts as
 * strength and `endurance`/`conditioning` count as cardio; `mobility` is excluded from the split.
 */
export type ExerciseCategory = 'strength' | 'endurance' | 'conditioning' | 'mobility' | 'power';

/**
 * Whether an exercise is logged as repetitions ("reps") or hold/duration in seconds ("seconds").
 * Strength/weightlifting movements use reps; isometrics (plank, levers, holds) and steady-state
 * endurance/cardio (running, cycling, jump rope) use seconds. Defaults to reps when omitted.
 */
export type ExerciseLoggingUnit = 'reps' | 'seconds';

/**
 * Anatomical slugs used by `react-native-body-highlighter` for the muscle map.
 * Subset we tag exercises against (finer than `MuscleGroup` — e.g. arms split into
 * biceps/triceps/forearm, back into upper-back/lower-back/trapezius).
 */
export type BodyPartSlug =
  | 'chest' | 'upper-back' | 'lower-back' | 'trapezius' | 'deltoids'
  | 'biceps' | 'triceps' | 'forearm'
  | 'abs' | 'obliques'
  | 'quadriceps' | 'hamstring' | 'gluteal' | 'adductors' | 'calves' | 'tibialis';

/** How strongly an exercise works a given muscle: 3 = primary, 2 = secondary, 1 = stabilizer. */
export interface MuscleActivation {
  slug: BodyPartSlug;
  level: 1 | 2 | 3;
}

export type WeightUnit = 'kg' | 'lbs';

export type WorkoutLogStatus = 'in_progress' | 'completed' | 'deleted';

export type DifficultyPerception = 1 | 2 | 3 | 4 | 5;

// Exercise from the exercise database
export interface Exercise {
  id: string;
  name: string;
  /** Spanish display name (from catalog merge); optional on custom exercises. */
  nameEs?: string;
  bodyRegion: BodyRegion;
  muscleGroup: MuscleGroup;
  movementType: MovementType;
  equipment: string[];
  videoUrl: string;
  /** Spanish-language technique explainer when available; falls back to `videoUrl` in UI if absent. */
  videoUrlEs?: string;
  instructions: string;
  substitutionsRecommended?: string[]; // Array of exercise IDs for recommended substitutions (optional for backward compatibility)
  /** How the middle log column is measured. Defaults to 'reps' when omitted. */
  loggingUnit?: ExerciseLoggingUnit;
  /** Strength vs endurance emphasis. Defaults to 'strength' when omitted. */
  category?: ExerciseCategory;
  /** Muscles worked and how strongly, for the muscle map. Falls back to `muscleGroup` when omitted. */
  muscleActivation?: MuscleActivation[];
}

export interface CustomExercise extends Exercise {
  userId: string;
  createdAt?: string;
  updatedAt?: string;
}

// Exercise as defined in a workout plan (generated by LLM)
export interface PlannedExercise {
  exerciseId: string;        // Reference to Exercise.id
  name: string;              // Exercise name for display
  sets: number;
  reps: string;              // Can be "8-12" or "10" or "AMRAP"
  restTimeSeconds?: number;  // Rest time between sets
  rir?: number;              // Reps in Reserve (0-5)
  notes?: string;            // Additional notes from coach
  alternatives?: { exerciseId: string; name: string }[]; // Alternative exercises (user picks one before logging)
}

// Workout plan as stored in step_details (generated by LLM)
export interface WorkoutPlan {
  dayName: string;           // e.g., "Upper Body Day", "Leg Day", "Full Body"
  dayType: string;           // e.g., "strength", "hypertrophy", "cardio", "mixed"
  estimatedDuration: number; // in minutes
  /** Session burn estimate (kcal), computed at plan creation from prescribed sets. */
  estimatedCaloriesBurned?: number;
  warmup?: string;           // Warmup instructions
  cooldown?: string;         // Cooldown instructions
  exercises: PlannedExercise[];
  recoveryHints?: {
    stretching?: string;
    fasciaMassage?: string;
    supplementation?: string;
    other?: string;
  };
}

// Individual exercise log entry (what user actually did)
export interface ExerciseLog {
  id?: number;                       // Local SQLite ID
  supabaseId?: number;               // Supabase ID after sync
  workoutLogId: number;              // Parent workout log ID
  exerciseId: string;                // Reference to Exercise.id
  exerciseName: string;              // Exercise name for display
  setNumber: number;                 // Which set (1, 2, 3...)
  weightValue?: number;              // Weight used (null for bodyweight)
  weightUnit?: WeightUnit;           // kg or lbs
  reps?: number;                     // Actual reps performed
  restTimeSeconds?: number;          // Actual rest taken
  rir?: number;                      // Reps in Reserve (0-5)
  difficultyPerception?: DifficultyPerception; // 1-5 rating
  comments?: string;                 // User notes
  completed?: boolean;               // Whether set is checked as done
  caloriesBurned?: number;          // Per-set kcal estimate (stored at log time)
  createdAt?: string;                // ISO timestamp
}

// Workout log entry (one per workout session)
export interface WorkoutLog {
  id?: number;                       // Local SQLite ID
  supabaseId?: number;               // Supabase ID after sync
  userId: string;                    // User ID
  workoutDate: string;               // ISO date string (YYYY-MM-DD)
  workoutDayName: string;            // e.g., "Leg Day", "Full Body"
  stepId?: string;                   // Link to action plan step (optional for legacy)
  status: WorkoutLogStatus;          // in_progress, completed, deleted
  exercises: ExerciseLog[];          // All exercise logs for this workout
  synced?: boolean;                  // Whether synced to Supabase
  createdAt?: string;                // ISO timestamp
  updatedAt?: string;                // ISO timestamp
}

// Pending workout log for sync retry
export interface PendingWorkoutLogData {
  localId: number;
  userId: string;
  workoutDate: string;
  workoutDayName: string;
  stepId?: string;
  status: WorkoutLogStatus;
  timestamp: number;
}

// Pending exercise log for sync retry
export interface PendingExerciseLogData {
  localId: number;
  workoutLogId: number;
  exerciseId: string;
  exerciseName: string;
  setNumber: number;
  weightValue?: number;
  weightUnit?: WeightUnit;
  reps?: number;
  restTimeSeconds?: number;
  rir?: number;
  difficultyPerception?: DifficultyPerception;
  comments?: string;
  timestamp: number;
}

// For displaying workout options from user's plan
export interface WorkoutDayOption {
  stepId: string;
  dayName: string;
  dayType?: string;
  exercises: PlannedExercise[];
  daysOfWeek?: string[];
  warmup?: string;
  cooldown?: string;
}

// English fallbacks for muscle group display names (also used as i18n defaultValues)
const MUSCLE_GROUP_FALLBACK: Record<MuscleGroup, string> = {
  chest: 'Chest',
  back: 'Back',
  shoulders: 'Shoulders',
  arms: 'Arms',
  legs: 'Legs (compound)',
  quads: 'Quads',
  hamstrings: 'Hamstrings',
  glutes: 'Glutes',
  adductors: 'Adductors',
  calves: 'Calves',
  abs: 'Abs',
  obliques: 'Obliques',
};

// Helper function to get muscle group display name
export const getMuscleGroupDisplayName = (muscleGroup: MuscleGroup): string => {
  const fallback = MUSCLE_GROUP_FALLBACK[muscleGroup] || muscleGroup;
  return i18n.t(`workout:muscleGroupNames.${muscleGroup}`, { defaultValue: fallback });
};

// English fallbacks for body region display names (also used as i18n defaultValues)
const BODY_REGION_FALLBACK: Record<BodyRegion, string> = {
  upper: 'Upper Body',
  lower: 'Lower Body',
  core: 'Core',
};

// Helper function to get body region display name
export const getBodyRegionDisplayName = (bodyRegion: BodyRegion): string => {
  const fallback = BODY_REGION_FALLBACK[bodyRegion] || bodyRegion;
  return i18n.t(`workout:bodyRegionNames.${bodyRegion}`, { defaultValue: fallback });
};

export const BODY_REGION_OPTIONS: BodyRegion[] = ['upper', 'lower', 'core'];

export const MUSCLE_GROUPS_BY_BODY_REGION: Record<BodyRegion, MuscleGroup[]> = {
  upper: ['chest', 'back', 'shoulders', 'arms'],
  lower: ['legs', 'quads', 'hamstrings', 'glutes', 'adductors', 'calves'],
  core: ['abs', 'obliques'],
};

// Helper function to get movement type display name
export const getMovementTypeDisplayName = (movementType: MovementType): string => {
  const fallback = movementType === 'compound' ? 'Compound' : 'Isolation';
  return i18n.t(`workout:movementTypeNames.${movementType}`, { defaultValue: fallback });
};

export const MOVEMENT_TYPE_OPTIONS: MovementType[] = ['compound', 'isolation'];

// English fallbacks for exercise category display names (also used as i18n defaultValues)
const EXERCISE_CATEGORY_FALLBACK: Record<ExerciseCategory, string> = {
  strength: 'Strength',
  endurance: 'Endurance',
  conditioning: 'Conditioning',
  mobility: 'Mobility',
  power: 'Power',
};

// Helper function to get exercise category display name
export const getExerciseCategoryDisplayName = (category: ExerciseCategory): string => {
  const fallback = EXERCISE_CATEGORY_FALLBACK[category] || category;
  return i18n.t(`workout:categoryNames.${category}`, { defaultValue: fallback });
};

export const EXERCISE_CATEGORY_OPTIONS: ExerciseCategory[] = ['strength', 'endurance', 'conditioning', 'mobility', 'power'];

// Helper to format rest time for display
export const formatRestTime = (seconds?: number): string => {
  if (!seconds) return '-';
  return `${seconds}s`;
};

// Helper to format RiR for display
export const formatRiR = (rir?: number): string => {
  if (rir === undefined || rir === null) return '-';
  return `RiR ${rir}`;
};

// Rest time options for dropdown
export const REST_TIME_OPTIONS = [
  { label: '15 seconds', value: 15 },
  { label: '30 seconds', value: 30 },
  { label: '45 seconds', value: 45 },
  { label: '60 seconds', value: 60 },
  { label: '90 seconds', value: 90 },
  { label: '2 minutes', value: 120 },
  { label: '2.5 minutes', value: 150 },
  { label: '3 minutes', value: 180 },
  { label: '4 minutes', value: 240 },
  { label: '5 minutes', value: 300 },
];

// RiR options for stepper (0 = to failure, 5 = very easy)
export const RIR_OPTIONS = [0, 1, 2, 3, 4, 5];

// Difficulty perception labels
export const DIFFICULTY_LABELS: Record<DifficultyPerception, string> = {
  1: 'Very Easy',
  2: 'Easy',
  3: 'Moderate',
  4: 'Hard',
  5: 'Very Hard',
};

// ============================================
// Activity / Cardio Logging Types
// ============================================

export type ActivityCategory =
  | 'running'
  | 'hiking'
  | 'cycling'
  | 'swimming'
  | 'winter_sports'
  | 'racket_sports'
  | 'team_sports'
  | 'water_sports'
  | 'martial_arts'
  | 'mind_body'
  | 'gym_cardio'
  | 'outdoor'
  | 'other';

export type ActivityIntensity = 'easy' | 'moderate' | 'hard' | 'max';

export interface ActivityType {
  id: string;
  name: string;
  icon: string;
  category: ActivityCategory;
  hasDistance: boolean;
  hasElevation: boolean;
  defaultUnit: 'km' | 'mi';
  /**
   * Wearables: when true the type is treated as strength-style for the
   * activity ↔ workout auto-link rule, even if `category` is e.g.
   * `gym_cardio`. Set on entries that map to wearable strength imports
   * (`traditionalStrengthTraining`, `STRENGTH_TRAINING`, `Weightlifting`, …).
   */
  strengthLike?: boolean;
}

export interface ActivityLog {
  id?: number;
  supabaseId?: number;
  userId: string;
  activityDate: string;
  activityType: string;
  activityName: string;
  durationMinutes: number;
  intensity: ActivityIntensity;
  distanceValue?: number;
  distanceUnit?: 'km' | 'mi';
  elevationGain?: number;
  caloriesBurned?: number;
  avgHeartRate?: number;
  notes?: string;
  synced?: boolean;
  createdAt?: string;
  updatedAt?: string;
  // Wearables v1: provenance + dedupe. All optional so existing manual-only
  // callers compile unchanged (defaults are applied in activity-storage.ts).
  source?: 'manual' | 'healthkit' | 'whoop' | 'garmin' | 'healthconnect';
  externalId?: string;
  caloriesSource?: 'provider' | 'estimated_met' | 'estimated_hr' | 'manual';
  caloriesConfidence?: 'high' | 'medium' | 'low';
  dedupeFingerprint?: string;
  startedAt?: string;
  endedAt?: string;
}

export const ACTIVITY_CATEGORIES: { id: ActivityCategory; label: string; icon: string }[] = [
  { id: 'running', label: 'Running', icon: '🏃' },
  { id: 'hiking', label: 'Hiking', icon: '🥾' },
  { id: 'cycling', label: 'Cycling', icon: '🚴' },
  { id: 'swimming', label: 'Swimming', icon: '🏊' },
  { id: 'winter_sports', label: 'Winter Sports', icon: '⛷️' },
  { id: 'racket_sports', label: 'Racket Sports', icon: '🎾' },
  { id: 'team_sports', label: 'Team Sports', icon: '⚽' },
  { id: 'water_sports', label: 'Water Sports', icon: '🚣' },
  { id: 'martial_arts', label: 'Martial Arts', icon: '🥊' },
  { id: 'mind_body', label: 'Mind & Body', icon: '🧘' },
  { id: 'gym_cardio', label: 'Gym Cardio', icon: '💪' },
  { id: 'outdoor', label: 'Outdoor', icon: '🧗' },
  { id: 'other', label: 'Other', icon: '🏅' },
];

export const ACTIVITY_TYPES: ActivityType[] = [
  // Running
  { id: 'run', name: 'Run', icon: '🏃', category: 'running', hasDistance: true, hasElevation: true, defaultUnit: 'km' },
  { id: 'trail_run', name: 'Trail Run', icon: '🌲', category: 'running', hasDistance: true, hasElevation: true, defaultUnit: 'km' },
  { id: 'sprint', name: 'Sprinting', icon: '⚡', category: 'running', hasDistance: true, hasElevation: false, defaultUnit: 'km' },
  { id: 'treadmill', name: 'Treadmill', icon: '🏃‍♂️', category: 'running', hasDistance: true, hasElevation: false, defaultUnit: 'km' },
  { id: 'walk', name: 'Walk', icon: '🚶', category: 'running', hasDistance: true, hasElevation: false, defaultUnit: 'km' },

  // Hiking
  { id: 'hike', name: 'Hike', icon: '🥾', category: 'hiking', hasDistance: true, hasElevation: true, defaultUnit: 'km' },
  { id: 'rucking', name: 'Rucking', icon: '🎒', category: 'hiking', hasDistance: true, hasElevation: true, defaultUnit: 'km' },
  { id: 'trail_walking', name: 'Trail Walking', icon: '🌿', category: 'hiking', hasDistance: true, hasElevation: true, defaultUnit: 'km' },
  { id: 'scrambling', name: 'Scrambling', icon: '⛰️', category: 'hiking', hasDistance: true, hasElevation: true, defaultUnit: 'km' },
  { id: 'fastpacking', name: 'Fastpacking', icon: '🏃‍♂️', category: 'hiking', hasDistance: true, hasElevation: true, defaultUnit: 'km' },

  // Cycling
  { id: 'road_cycling', name: 'Road Cycling', icon: '🚴', category: 'cycling', hasDistance: true, hasElevation: true, defaultUnit: 'km' },
  { id: 'mountain_biking', name: 'Mountain Biking', icon: '🚵', category: 'cycling', hasDistance: true, hasElevation: true, defaultUnit: 'km' },
  { id: 'gravel_cycling', name: 'Gravel', icon: '🚴‍♂️', category: 'cycling', hasDistance: true, hasElevation: true, defaultUnit: 'km' },
  { id: 'indoor_cycling', name: 'Indoor / Spin', icon: '🔄', category: 'cycling', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'stationary_bike', name: 'Stationary Bike', icon: '🚲', category: 'cycling', hasDistance: false, hasElevation: false, defaultUnit: 'km' },

  // Swimming
  { id: 'pool_swim', name: 'Pool Swim', icon: '🏊', category: 'swimming', hasDistance: true, hasElevation: false, defaultUnit: 'km' },
  { id: 'open_water_swim', name: 'Open Water', icon: '🌊', category: 'swimming', hasDistance: true, hasElevation: false, defaultUnit: 'km' },

  // Winter Sports
  { id: 'downhill_skiing', name: 'Downhill Skiing', icon: '⛷️', category: 'winter_sports', hasDistance: false, hasElevation: true, defaultUnit: 'km' },
  { id: 'cross_country_skiing', name: 'Cross-Country Skiing', icon: '🎿', category: 'winter_sports', hasDistance: true, hasElevation: true, defaultUnit: 'km' },
  { id: 'snowboarding', name: 'Snowboarding', icon: '🏂', category: 'winter_sports', hasDistance: false, hasElevation: true, defaultUnit: 'km' },
  { id: 'ice_skating', name: 'Ice Skating', icon: '⛸️', category: 'winter_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'snowshoeing', name: 'Snowshoeing', icon: '❄️', category: 'winter_sports', hasDistance: true, hasElevation: true, defaultUnit: 'km' },
  { id: 'ski_mountaineering', name: 'Ski Mountaineering', icon: '🏔️', category: 'winter_sports', hasDistance: true, hasElevation: true, defaultUnit: 'km' },

  // Racket Sports
  { id: 'tennis', name: 'Tennis', icon: '🎾', category: 'racket_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'padel', name: 'Padel', icon: '🏓', category: 'racket_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'badminton', name: 'Badminton', icon: '🏸', category: 'racket_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'squash', name: 'Squash', icon: '🎾', category: 'racket_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'pickleball', name: 'Pickleball', icon: '🏓', category: 'racket_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'table_tennis', name: 'Table Tennis', icon: '🏓', category: 'racket_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },

  // Team Sports
  { id: 'soccer', name: 'Soccer', icon: '⚽', category: 'team_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'basketball', name: 'Basketball', icon: '🏀', category: 'team_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'football', name: 'Football', icon: '🏈', category: 'team_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'volleyball', name: 'Volleyball', icon: '🏐', category: 'team_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'baseball', name: 'Baseball', icon: '⚾', category: 'team_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'rugby', name: 'Rugby', icon: '🏉', category: 'team_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'hockey', name: 'Hockey', icon: '🏒', category: 'team_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'lacrosse', name: 'Lacrosse', icon: '🥍', category: 'team_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'cricket', name: 'Cricket', icon: '🏏', category: 'team_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'handball', name: 'Handball', icon: '🤾', category: 'team_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'softball', name: 'Softball', icon: '🥎', category: 'team_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'water_polo', name: 'Water Polo', icon: '🤽', category: 'team_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },

  // Water Sports
  { id: 'rowing', name: 'Rowing', icon: '🚣', category: 'water_sports', hasDistance: true, hasElevation: false, defaultUnit: 'km' },
  { id: 'kayaking', name: 'Kayaking', icon: '🛶', category: 'water_sports', hasDistance: true, hasElevation: false, defaultUnit: 'km' },
  { id: 'canoeing', name: 'Canoeing', icon: '🛶', category: 'water_sports', hasDistance: true, hasElevation: false, defaultUnit: 'km' },
  { id: 'paddleboarding', name: 'Paddleboarding', icon: '🏄', category: 'water_sports', hasDistance: true, hasElevation: false, defaultUnit: 'km' },
  { id: 'surfing', name: 'Surfing', icon: '🏄', category: 'water_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'windsurfing', name: 'Windsurfing', icon: '🌬️', category: 'water_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'kitesurfing', name: 'Kitesurfing', icon: '🪁', category: 'water_sports', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'sailing', name: 'Sailing', icon: '⛵', category: 'water_sports', hasDistance: true, hasElevation: false, defaultUnit: 'km' },

  // Martial Arts
  { id: 'boxing', name: 'Boxing', icon: '🥊', category: 'martial_arts', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'kickboxing', name: 'Kickboxing', icon: '🦶', category: 'martial_arts', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'mma', name: 'MMA', icon: '🥋', category: 'martial_arts', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'judo', name: 'Judo', icon: '🥋', category: 'martial_arts', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'jiu_jitsu', name: 'Jiu-Jitsu', icon: '🥋', category: 'martial_arts', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'wrestling', name: 'Wrestling', icon: '🤼', category: 'martial_arts', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'karate', name: 'Karate', icon: '🥋', category: 'martial_arts', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'taekwondo', name: 'Taekwondo', icon: '🥋', category: 'martial_arts', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'muay_thai', name: 'Muay Thai', icon: '🥊', category: 'martial_arts', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'fencing', name: 'Fencing', icon: '🤺', category: 'martial_arts', hasDistance: false, hasElevation: false, defaultUnit: 'km' },

  // Mind & Body
  { id: 'yoga', name: 'Yoga', icon: '🧘', category: 'mind_body', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'pilates', name: 'Pilates', icon: '🧘‍♀️', category: 'mind_body', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'tai_chi', name: 'Tai Chi', icon: '☯️', category: 'mind_body', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'stretching', name: 'Stretching', icon: '🤸', category: 'mind_body', hasDistance: false, hasElevation: false, defaultUnit: 'km' },

  // Gym Cardio
  { id: 'elliptical', name: 'Elliptical', icon: '🏋️', category: 'gym_cardio', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'stair_climber', name: 'Stair Climber', icon: '🪜', category: 'gym_cardio', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'rowing_machine', name: 'Rowing Machine', icon: '🚣', category: 'gym_cardio', hasDistance: true, hasElevation: false, defaultUnit: 'km' },
  { id: 'jump_rope', name: 'Jump Rope', icon: '⏭️', category: 'gym_cardio', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'hiit_class', name: 'HIIT Class', icon: '🔥', category: 'gym_cardio', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'dance', name: 'Dance / Zumba', icon: '💃', category: 'gym_cardio', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'aerobics', name: 'Aerobics', icon: '🤸‍♀️', category: 'gym_cardio', hasDistance: false, hasElevation: false, defaultUnit: 'km' },

  // Outdoor
  { id: 'climbing', name: 'Climbing', icon: '🧗', category: 'outdoor', hasDistance: false, hasElevation: true, defaultUnit: 'km' },
  { id: 'bouldering', name: 'Bouldering', icon: '🪨', category: 'outdoor', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'horseback_riding', name: 'Horseback Riding', icon: '🐎', category: 'outdoor', hasDistance: true, hasElevation: false, defaultUnit: 'km' },
  { id: 'golf', name: 'Golf', icon: '⛳', category: 'outdoor', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'skateboarding', name: 'Skateboarding', icon: '🛹', category: 'outdoor', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'roller_skating', name: 'Roller Skating', icon: '🛼', category: 'outdoor', hasDistance: true, hasElevation: false, defaultUnit: 'km' },
  { id: 'parkour', name: 'Parkour', icon: '🏃‍♂️', category: 'outdoor', hasDistance: false, hasElevation: false, defaultUnit: 'km' },

  // Strength-style (wearable imports)
  { id: 'strength_training', name: 'Strength Training', icon: '🏋️', category: 'other', hasDistance: false, hasElevation: false, defaultUnit: 'km', strengthLike: true },
  { id: 'crossfit', name: 'CrossFit', icon: '💪', category: 'other', hasDistance: false, hasElevation: false, defaultUnit: 'km', strengthLike: true },
  { id: 'calisthenics', name: 'Calisthenics', icon: '🤸', category: 'other', hasDistance: false, hasElevation: false, defaultUnit: 'km', strengthLike: true },

  // Other
  { id: 'custom', name: 'Custom Activity', icon: '🏅', category: 'other', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
  { id: 'other_activity', name: 'Other Activity', icon: '🏅', category: 'other', hasDistance: false, hasElevation: false, defaultUnit: 'km' },
];

export const INTENSITY_OPTIONS: { value: ActivityIntensity; label: string; color: string }[] = [
  { value: 'easy', label: 'Easy', color: '#4CAF50' },
  { value: 'moderate', label: 'Moderate', color: '#FF9800' },
  { value: 'hard', label: 'Hard', color: '#F47C3C' },
  { value: 'max', label: 'Max', color: '#F44336' },
];

export const getActivityTypeById = (id: string): ActivityType | undefined =>
  ACTIVITY_TYPES.find(a => a.id === id);

export const getActivityTypesByCategory = (category: ActivityCategory): ActivityType[] =>
  ACTIVITY_TYPES.filter(a => a.category === category);

