import { StyleSheet } from 'react-native';
import { BrandColors } from '../constants/Colors';
import { FontFamily, FontSize, LetterSpacing, LineHeight, TextStyles } from '../constants/Typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BrandColors.backgroundPrimary,
  },
  scrollView: {
    flex: 1,
  },
  /** Clears the bottom tab bar (raised + log button intrudes ~32px into content). */
  scrollContent: {
    paddingBottom: 18,
  },
  section: {
    backgroundColor: BrandColors.backgroundSecondary,
    padding: 20,
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: BrandColors.cardBorder,
  },
  nutritionSection: {
    paddingBottom: 14,
  },
  chartSection: {
    paddingBottom: 12,
  },

  // =========================================================================
  // Consistency Score Ring
  // =========================================================================
  headerContainer: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: BrandColors.backgroundPrimary,
    paddingBottom: 24,
  },
  scoreSection: {
    alignItems: 'center',
    position: 'relative',
    backgroundColor: 'transparent',
  },
  scoreSectionBgImageContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  scoreSectionBgImage: {
    width: '100%',
    height: '100%',
    opacity: 0.5,
  },
  // Slight centered zoom used for female background to focus the subject when used as a header background
  bgImageZoom: {
    transform: [{ scale: 1.35 }, { translateY: 40 }],
    alignSelf: 'center',
  },
  scoreSectionGradientSvg: {
    position: 'absolute',
    top: 0,
    left: 0,
    pointerEvents: 'none',
  },
  scoreGradientOverlay: {
    alignItems: 'center',
    paddingTop: 34,
    paddingBottom: 8,
    paddingHorizontal: 20,
    width: '100%',
    zIndex: 1,
    position: 'relative' as const,
  },
  scoreLabelRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginBottom: 20,
    gap: 8,
  },
  scoreModeRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginTop: 10,
    marginBottom: 12,
  },
  scoreLabel: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.metaSmall,
    color: BrandColors.accent,
    letterSpacing: LetterSpacing.extraWide,
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  scoreModeToggle: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    gap: 3,
  },
  scoreModeText: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: 10,
    color: '#9AA3A6',
  },
  scoreModeChevron: {
    fontSize: 8,
    color: '#9AA3A6',
    marginTop: -1,
  },
  scoreModeDropdown: {
    position: 'absolute' as const,
    top: 28,
    right: 20,
    backgroundColor: '#1A2426',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2A3638',
    overflow: 'hidden' as const,
    zIndex: 100,
    elevation: 10,
  },
  scoreModeOption: {
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  scoreModeOptionActive: {
    backgroundColor: 'rgba(244, 124, 60, 0.12)',
  },
  scoreModeOptionText: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: 12,
    color: '#9AA3A6',
  },
  scoreModeOptionTextActive: {
    color: BrandColors.accent,
    fontFamily: FontFamily.bodySemiBold,
  },
  scoreArrow: {
    position: 'absolute',
    right: 2,
    top: 0,
    bottom: 0,
    width: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scoreArrowText: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: 24,
    color: BrandColors.textTertiary,
    lineHeight: 28,
    opacity: 0.6,
  },
  ringContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  ringCenterText: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ translateY: -8 }], // slightly elevate center text inside the rings
  },
  scoreNumber: {
    fontFamily: FontFamily.displayBold,
    fontSize: 42,
    color: BrandColors.accent,
    lineHeight: 48,
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  scoreTitle: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.metaSmall,
    color: BrandColors.textTertiary,
    letterSpacing: LetterSpacing.extraWide,
    marginTop: 2,
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  scoreLegend: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: 28,
    marginTop: 8,
    marginBottom: 4,
  },
  scoreLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  scoreLegendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginTop: 3,
  },
  scoreLegendText: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.metaSmall,
    color: BrandColors.textTertiary,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  scoreLegendValue: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    color: BrandColors.accent,
    marginTop: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  scoreLegendValueMuted: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    color: BrandColors.textSecondary,
    marginTop: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  scoreLegendNoData: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.metaSmall,
    color: BrandColors.textTertiary,
    marginTop: 3,
    fontStyle: 'italic',
    opacity: 0.6,
    letterSpacing: 0.3,
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },

  // =========================================================================
  // Weekly Tracker Table
  // =========================================================================
  trackerSection: {
    backgroundColor: BrandColors.backgroundSecondary,
    marginHorizontal: 20,
    marginTop: 4,
    marginBottom: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: BrandColors.cardBorder,
    padding: 16,
    paddingBottom: 12,
  },
  // Today's workout ribbon - Electric border effect
  workoutRibbonContainer: {
    position: 'relative',
    marginHorizontal: 20,
    marginTop: 12,
    marginBottom: 0,
    overflow: 'visible',
  },
  workoutRibbon: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    // Make the "Today" ribbon 30% shorter (reduce height via vertical padding)
    paddingVertical: 13, // ~30% shorter than previous 18
    paddingLeft: 20,
    paddingRight: 16,
    borderRadius: 16,
    backgroundColor: '#0C1416',
    borderWidth: 1,
    borderColor: 'rgba(255, 140, 107, 0.25)',
    overflow: 'hidden',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 8,
    zIndex: 2,
  },
  workoutRibbonGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 16,
  },
  workoutRibbonGlowBar: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
    backgroundColor: '#FF6B35',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    borderTopLeftRadius: 16,
    borderBottomLeftRadius: 16,
    zIndex: 1,
  },
  workoutRibbonContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 2,
  },
  workoutRibbonLeft: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 4,
    flex: 1,
  },
  workoutRibbonLabel: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.metaSmall,
    color: '#FF8C6B',
    letterSpacing: LetterSpacing.wide,
    textTransform: 'uppercase',
    textShadowColor: 'rgba(255, 107, 53, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  workoutRibbonDayName: {
    fontFamily: FontFamily.bodySemiBold,
    // 20% smaller than standard body text
    fontSize: FontSize.body * 0.8,
    color: BrandColors.textPrimary,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    flexWrap: 'wrap',
    flexShrink: 1,
  },
  workoutRibbonCta: {
    fontFamily: FontFamily.bodySemiBold,
    // 20% smaller than standard body text
    fontSize: FontSize.body * 0.8,
    color: '#FFB599',
    textShadowColor: 'rgba(255, 107, 53, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  workoutRibbonArrow: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: 32,
    color: '#FFB599',
    marginLeft: 10,
    lineHeight: 32,
    zIndex: 2,
    textShadowColor: 'rgba(255, 107, 53, 0.4)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  trackerTitle: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.metaSmall,
    color: BrandColors.accent,
    letterSpacing: LetterSpacing.extraWide,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  trackerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  trackerRowLabel: {
    width: 58,
    paddingRight: 4,
  },
  trackerRowLabelText: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.metaSmall,
    color: BrandColors.textTertiary,
    letterSpacing: 0.3,
  },
  trackerHeaderCell: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 6,
    borderRadius: 6,
  },
  trackerTodayTop: {
    backgroundColor: 'transparent',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: 'rgba(244, 124, 60, 0.25)',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  trackerDayText: {
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.metaSmall,
    color: BrandColors.textTertiary,
    letterSpacing: 0.3,
  },
  trackerTodayText: {
    color: BrandColors.accent,
  },
  trackerCell: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    borderRadius: 6,
  },
  trackerTodayMiddle: {
    backgroundColor: 'transparent',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: 'rgba(244, 124, 60, 0.25)',
    borderRadius: 0,
  },
  trackerTodayBottom: {
    backgroundColor: 'transparent',
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: 'rgba(244, 124, 60, 0.25)',
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },

  // Nutrition / Training cell indicators
  trackerIndicator: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: BrandColors.cardBorder,
    backgroundColor: BrandColors.backgroundTertiary,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trackerIndicatorFill: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(244, 124, 60, 0.3)',
    borderRadius: 4,
  },
  trackerIndicatorPartial: {
    backgroundColor: 'rgba(244, 124, 60, 0.35)',
  },
  trackerIndicatorFull: {
    backgroundColor: BrandColors.accent,
  },
  trackerIndicatorCount: {
    fontFamily: FontFamily.bodyMedium,
    fontSize: 11,
    color: BrandColors.textPrimary,
    textAlign: 'center',
    lineHeight: 28,
  },
  trackerNutritionText: {
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.metaSmall,
    lineHeight: 28,
    textAlign: 'center',
  },

  // Training states
  trackerIndicatorLogged: {
    backgroundColor: BrandColors.accent,
    borderColor: BrandColors.accent,
  },
  trackerIndicatorPlanned: {
    backgroundColor: BrandColors.backgroundTertiary,
    borderColor: BrandColors.inputBorder,
    borderStyle: 'dashed',
  },
  trackerCheckmark: {
    fontFamily: FontFamily.bodyMedium,
    fontSize: 13,
    color: BrandColors.backgroundPrimary,
    lineHeight: 28,
    textAlign: 'center',
  },
  workoutCountBadge: {
    position: 'absolute' as const,
    top: -4,
    right: -4,
    backgroundColor: BrandColors.accent,
    borderRadius: 7,
    width: 14,
    height: 14,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    borderWidth: 1.5,
    borderColor: BrandColors.backgroundPrimary,
  },
  workoutCountBadgeText: {
    fontFamily: FontFamily.bodyMedium,
    fontSize: 8,
    color: BrandColors.backgroundPrimary,
    lineHeight: 10,
    textAlign: 'center' as const,
  },
  trackerMissed: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: 11,
    color: BrandColors.textTertiary,
    lineHeight: 28,
    textAlign: 'center',
  },
  trackerIndicatorOff: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: BrandColors.backgroundPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0.35,
  },
  trackerOffDash: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: 11,
    color: BrandColors.textTertiary,
    lineHeight: 32,
  },
  catchUpNudge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: 'rgba(244, 124, 60, 0.08)',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginTop: 10,
    gap: 8,
  },
  catchUpNudgeText: {
    flex: 1,
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.metaSmall,
    color: BrandColors.accentSoft,
    lineHeight: 16,
  },
  catchUpNudgeDismiss: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: 14,
    color: BrandColors.textTertiary,
    paddingLeft: 4,
  },

  // =========================================================================
  // Existing styles (preserved and refined)
  // =========================================================================
  greeting: {
    ...TextStyles.sectionHeadline,
    color: BrandColors.textPrimary,
    marginBottom: 20,
  },
  tasksContainer: {
    position: 'relative',
  },
  tasksGrid: {
    gap: 12,
    paddingRight: 20,
  },
  tasksScroll: {
    marginHorizontal: -20,
    paddingHorizontal: 20,
  },
  taskCard: {
    backgroundColor: BrandColors.backgroundTertiary,
    borderRadius: 12,
    padding: 14,
    flexDirection: 'column',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: BrandColors.cardBorder,
    width: 135,
    minHeight: 110,
  },
  taskCardCompleted: {
    backgroundColor: BrandColors.backgroundSecondary,
    borderColor: BrandColors.divider,
    opacity: 0.5,
  },
  taskEmoji: {
    fontSize: 22,
    marginRight: 0,
    marginBottom: 6,
  },
  taskCategory: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.meta,
    color: BrandColors.textPrimary,
    marginBottom: 4,
    flexWrap: 'wrap',
    lineHeight: 16,
  },
  taskDetail: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.bodySmall,
    color: BrandColors.textSecondary,
    lineHeight: LineHeight.bodySmall,
  },
  taskCheckbox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
  },
  checkbox: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: BrandColors.textTertiary,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 0,
  },
  checkboxCompleted: {
    backgroundColor: BrandColors.accent,
    borderColor: BrandColors.accent,
  },
  checkmark: {
    color: BrandColors.backgroundPrimary,
    fontSize: 16,
    fontWeight: 'bold',
  },
  checkboxLabel: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.meta,
    color: BrandColors.textSecondary,
    marginLeft: 8,
  },
  checkboxLabelCompleted: {
    color: BrandColors.accent,
    fontFamily: FontFamily.bodySemiBold,
  },
  sectionTitle: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.metaSmall,
    color: BrandColors.accent,
    letterSpacing: LetterSpacing.extraWide,
    textTransform: 'uppercase',
    marginBottom: 14,
  },
  sectionTitleInRow: {
    marginBottom: 0,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  nutritionSectionHeader: {
    gap: 4,
    marginBottom: 6,
  },
  nutritionTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  nutritionSectionTitleFlex: {
    flex: 1,
    flexShrink: 1,
  },
  cameraButtonInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flexShrink: 0,
    marginTop: -1,
  },
  deviationCard: {
    marginHorizontal: 20,
    marginTop: 12,
    marginBottom: 4,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: BrandColors.accent,
    backgroundColor: BrandColors.backgroundSecondary,
    gap: 6,
  },
  deviationCardTitle: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: 14,
    color: BrandColors.accent,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  deviationCardBody: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: 13,
    color: BrandColors.textPrimary,
    lineHeight: 18,
  },
  deviationCardCta: {
    fontFamily: FontFamily.bodyMedium,
    fontSize: 13,
    color: BrandColors.accent,
    marginTop: 4,
  },
  cameraButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    zIndex: 1,
  },
  cameraEmoji: {
    fontSize: 18,
  },
  cameraText: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.metaSmall,
    color: BrandColors.accent,
    lineHeight: FontSize.metaSmall + 4,
  },
  // Wearables v1: pill surfacing today's adjusted calorie target + breakdown.
  adjustedTargetPill: {
    marginTop: 8,
    marginBottom: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(244, 124, 60, 0.08)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(244, 124, 60, 0.25)',
    gap: 2,
  },
  adjustedTargetText: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    color: BrandColors.textPrimary,
  },
  adjustedTargetSub: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.meta,
    color: BrandColors.textSecondary,
  },
  adjustedTargetFootnote: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.metaSmall,
    color: BrandColors.textTertiary,
    lineHeight: 16,
    marginTop: 4,
  },
  subtitle: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.bodySmall,
    color: BrandColors.textSecondary,
    marginBottom: 20,
    lineHeight: LineHeight.bodySmall,
  },
  chartPlaceholder: {
    height: 160,
    backgroundColor: BrandColors.backgroundTertiary,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: BrandColors.divider,
  },
  placeholderText: {
    color: BrandColors.textTertiary,
    fontSize: FontSize.bodySmall,
    fontFamily: FontFamily.bodyRegular,
  },
  feedCard: {
    borderRadius: 16,
    backgroundColor: BrandColors.backgroundTertiary,
    padding: 20,
    borderWidth: 1,
    borderColor: BrandColors.cardBorder,
  },
  feedCardSpacing: {
    marginTop: 14,
  },
  feedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  feedThumbnail: {
    fontSize: 36,
  },
  feedBadge: {
    backgroundColor: BrandColors.accent,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
  },
  articleBadge: {
    backgroundColor: BrandColors.accentSoft,
  },
  feedBadgeText: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.metaSmall,
    letterSpacing: 0.5,
  },
  feedTitle: {
    ...TextStyles.bodySemiBold,
    fontSize: FontSize.body,
    color: BrandColors.textPrimary,
    marginBottom: 10,
    lineHeight: LineHeight.body,
  },
  feedSubtitle: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.bodySmall,
    color: BrandColors.textSecondary,
    lineHeight: LineHeight.bodySmall,
    marginBottom: 14,
  },
  feedLink: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.bodySmall,
    color: BrandColors.accent,
  },
  videoContainer: {
    width: '100%',
    height: 200,
    marginTop: 14,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: BrandColors.backgroundPrimary,
    position: 'relative',
  },
  videoThumbnail: {
    width: '100%',
    height: '100%',
  },
  playButtonOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: BrandColors.overlayMedium,
  },
  playButton: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: BrandColors.textPrimary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  playButtonText: {
    fontSize: 26,
    color: BrandColors.accent,
    marginLeft: 4,
  },
  congratsBanner: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: BrandColors.backgroundSecondary,
    padding: 14,
    borderRadius: 12,
    marginHorizontal: 20,
    zIndex: 10,
    borderWidth: 1,
    borderColor: BrandColors.accent,
  },
  congratsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  congratsIcon: {
    width: 20,
    height: 20,
    marginRight: 8,
  },
  congratsText: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.bodySmall,
    color: BrandColors.accent,
    textAlign: 'center',
  },
  streakTitle: {
    ...TextStyles.bodySemiBold,
    fontSize: FontSize.subheadline,
    color: BrandColors.textPrimary,
    marginBottom: 10,
    letterSpacing: 0.3,
  },
  streakSubtitle: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.bodySmall,
    color: BrandColors.textSecondary,
    marginBottom: 24,
    lineHeight: LineHeight.bodySmall,
    opacity: 0.85,
  },
  consistencyExplanation: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.bodySmall,
    color: BrandColors.textTertiary,
    lineHeight: LineHeight.body,
    marginBottom: 10,
    letterSpacing: 0.15,
  },
  streakThresholdNote: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.meta,
    color: BrandColors.textTertiary,
    opacity: 0.6,
    marginBottom: 20,
    letterSpacing: 0.1,
  },
  streakThresholdNoteHighlight: {
    fontFamily: FontFamily.bodySemiBold,
    color: BrandColors.accent,
    opacity: 1,
  },
  svgChartContainer: {
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 6,
  },
  chartLegendContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
  },
  chartLegendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: BrandColors.accent,
    marginRight: 8,
  },
  chartLegend: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.meta,
    color: BrandColors.textSecondary,
    textAlign: 'center',
  },
  tooltip: {
    position: 'absolute',
    alignSelf: 'center',
    backgroundColor: BrandColors.backgroundTertiary,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    zIndex: 10,
    minWidth: 44,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: BrandColors.cardBorder,
  },
  tooltipText: {
    color: BrandColors.textPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.metaSmall,
  },
  streakDetailModal: {
    backgroundColor: BrandColors.backgroundSecondary,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 40,
    width: '100%',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: BrandColors.cardBorder,
  },
  streakDetailHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: BrandColors.textTertiary,
    alignSelf: 'center',
    marginBottom: 20,
    opacity: 0.5,
  },
  seeOthersConsistencyButton: {
    marginTop: 20,
    backgroundColor: BrandColors.accent,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  seeOthersConsistencyButtonText: {
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
    color: '#0B1114',
    letterSpacing: 0.3,
  },
  mealLogModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: BrandColors.overlayDark,
  },
  mealLogOptionsModalContent: {
    backgroundColor: BrandColors.backgroundSecondary,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 40,
    width: '100%',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: BrandColors.cardBorder,
    maxHeight: '70%',
  },
  mealLogOptionsTitle: {
    ...TextStyles.sectionHeadline,
    fontSize: 21,
    color: BrandColors.textPrimary,
    marginBottom: 12,
    textAlign: 'center',
  },
  mealLogOptionsSubtitle: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: 14,
    color: BrandColors.textSecondary,
    marginBottom: 14,
    textAlign: 'center',
  },
  mealLogOptionsButtons: {
    flexDirection: 'column',
    gap: 9,
    paddingVertical: 6,
  },
  mealLogOptionButton: {
    backgroundColor: BrandColors.backgroundTertiary,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: BrandColors.cardBorder,
  },
  mealOptionEmoji: {
    fontSize: 35,
    marginBottom: 7,
  },
  mealOptionIcon: {
    width: 35,
    height: 35,
    marginBottom: 7,
  },
  mealOptionIconWrapper: {
    marginBottom: 7,
  },
  mealOptionTitle: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: 14,
    color: BrandColors.textPrimary,
    marginBottom: 3,
    textAlign: 'center',
  },
  mealOptionSubtitle: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: 12,
    color: BrandColors.textSecondary,
    textAlign: 'center',
  },
});
