import { StyleSheet } from 'react-native';
import { BrandColors } from '../constants/Colors';
import { FontFamily, FontSize, LineHeight, TextStyles } from '../constants/Typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BrandColors.backgroundPrimary,
    padding: 24,
    justifyContent: 'center',
  },
  
  // Field screen scrolling styles
  fieldScrollView: {
    flex: 1,
  },
  fieldContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingVertical: 24,
    justifyContent: 'space-between',
  },
  fieldFooter: {
    paddingHorizontal: 24,
    paddingBottom: 24,
    paddingTop: 12,
    backgroundColor: BrandColors.backgroundPrimary,
    borderTopWidth: 1,
    borderTopColor: BrandColors.divider,
  },
  
  // Title styles
  title: {
    ...TextStyles.heroHeadline,
    color: BrandColors.textPrimary,
    textAlign: 'center',
    marginTop: 16,
    marginBottom: 12,
  },
  subtitle: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.body,
    color: BrandColors.textSecondary,
    textAlign: 'center',
    marginBottom: 48,
    lineHeight: LineHeight.body,
  },
  
  // Coach selection
  coachList: {
    flex: 1,
    marginVertical: 24,
  },
  coachCard: {
    backgroundColor: BrandColors.backgroundSecondary,
    borderRadius: 16,
    padding: 24,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: BrandColors.cardBorder,
    alignItems: 'center',
    flexDirection: 'column',
    minHeight: 200,
    position: 'relative',
  },
  coachCardSelected: {
    borderColor: BrandColors.accent,
    backgroundColor: BrandColors.backgroundTertiary,
  },
  typeBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: BrandColors.accent,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    zIndex: 10,
  },
  typeBadgeText: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.metaSmall,
    textTransform: 'none',
  },
  coachImageContainer: {
    position: 'relative',
    marginBottom: 24,
    alignItems: 'center',
    alignSelf: 'center',
  },
  coachImagePlaceholder: {
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: BrandColors.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  coachImage: {
    width: 180,
    height: 180,
    borderRadius: 90,
  },
  coachImageText: {
    color: BrandColors.backgroundPrimary,
    fontSize: 72,
    fontFamily: FontFamily.displayBold,
  },
  newBadge: {
    position: 'absolute',
    top: -8,
    left: -8,
    backgroundColor: BrandColors.success,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
  },
  newBadgeText: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.metaSmall,
  },
  aiBadge: {
    backgroundColor: BrandColors.accentSoft,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 24,
    marginLeft: 10,
  },
  aiBadgeText: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.bodySmall,
  },
  humanAiBadge: {
    backgroundColor: BrandColors.accent,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 24,
  },
  humanAiBadgeText: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.meta,
  },
  badgeContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  coachName: {
    ...TextStyles.sectionHeadline,
    fontSize: 24,
    color: BrandColors.textPrimary,
    marginBottom: 14,
    textAlign: 'center',
    width: '100%',
  },
  coachShortDescription: {
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.subheadline * 0.8,
    color: BrandColors.textSecondary,
    textAlign: 'center',
    lineHeight: 21,
    marginBottom: 14,
    width: '100%',
  },
  coachFullDescription: {
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.subheadline * 0.8,
    color: BrandColors.textSecondary,
    lineHeight: 24,
    textAlign: 'center',
    width: '100%',
  },
  bulletContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  bulletPoint: {
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.body,
    color: BrandColors.textSecondary,
    marginRight: 10,
    marginTop: 0,
  },
  
  // Primary button (CTA)
  nextButton: {
    backgroundColor: BrandColors.accent,
    paddingVertical: 18,
    paddingHorizontal: 36,
    borderRadius: 28,
    marginTop: 36,
    marginBottom: 36,
    marginHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextButtonText: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    letterSpacing: 0.5,
  },
  
  // Form styles
  form: {
    flex: 1,
  },
  inputGroup: {
    marginBottom: 28,
  },
  label: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    color: BrandColors.textPrimary,
    marginBottom: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: BrandColors.inputBorder,
    borderRadius: 12,
    padding: 18,
    fontSize: FontSize.body,
    fontFamily: FontFamily.bodyRegular,
    backgroundColor: BrandColors.inputBackground,
    color: BrandColors.textPrimary,
    marginTop: 6,
  },
  inputError: {
    borderColor: BrandColors.error,
    borderWidth: 2,
  },
  validationError: {
    color: BrandColors.error,
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.bodySmall,
    marginTop: 10,
    marginLeft: 4,
  },
  pickerButton: {
    borderWidth: 1,
    borderColor: BrandColors.inputBorder,
    borderRadius: 12,
    backgroundColor: BrandColors.inputBackground,
    padding: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 58,
    marginTop: 6,
  },
  pickerButtonText: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.body,
    color: BrandColors.textPrimary,
    flex: 1,
  },
  pickerPlaceholder: {
    color: BrandColors.textTertiary,
  },
  pickerArrow: {
    fontSize: FontSize.meta,
    color: BrandColors.textTertiary,
    marginLeft: 10,
  },
  submitButton: {
    backgroundColor: BrandColors.success,
    padding: 18,
    borderRadius: 12,
    marginTop: 36,
  },
  submitButtonText: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    textAlign: 'center',
  },
  
  // Overview styles
  overviewHeader: {
    alignItems: 'center',
    marginBottom: 36,
  },
  overviewCoachName: {
    ...TextStyles.bodySemiBold,
    fontSize: FontSize.subheadline,
    color: BrandColors.textPrimary,
    marginTop: 14,
  },
  overviewContent: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  overviewTitle: {
    ...TextStyles.sectionHeadline,
    fontSize: 22,
    color: BrandColors.textPrimary,
    marginBottom: 36,
    lineHeight: 30,
    textAlign: 'center',
  },
  overviewSteps: {
    marginBottom: 36,
  },
  overviewStep: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 28,
    paddingHorizontal: 16,
  },
  overviewStepNumber: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: BrandColors.accent,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 18,
    flexShrink: 0,
  },
  overviewStepNumberText: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  overviewStepContent: {
    flex: 1,
    paddingTop: 2,
  },
  overviewStepTitle: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    color: BrandColors.textPrimary,
    marginBottom: 8,
    lineHeight: 24,
  },
  overviewStepDescription: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.bodySmall,
    color: BrandColors.textSecondary,
    lineHeight: LineHeight.bodySmall,
  },
  overviewStepText: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.body,
    color: BrandColors.textPrimary,
    flex: 1,
    lineHeight: 24,
  },
  overviewFooter: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.body,
    color: BrandColors.textSecondary,
    lineHeight: 24,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingHorizontal: 16,
  },
  letsGoButton: {
    backgroundColor: BrandColors.success,
    padding: 18,
    borderRadius: 12,
    marginTop: 18,
    marginBottom: 24,
  },
  letsGoButtonText: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    textAlign: 'center',
  },
  unsupportedWidget: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.bodySmall,
    color: BrandColors.textTertiary,
    fontStyle: 'italic',
    padding: 14,
    backgroundColor: BrandColors.backgroundSecondary,
    borderRadius: 12,
  },
  
  // Field screen styles
  fieldScreenContent: {
    flex: 1,
  },
  fieldHeader: {
    alignItems: 'center',
    marginBottom: 36,
  },
  coachImageSmall: {
    width: 64,
    height: 64,
    borderRadius: 32,
    marginBottom: 14,
  },
  coachImagePlaceholderSmall: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: BrandColors.accent,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
  },
  coachImageTextSmall: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.displayBold,
    fontSize: 26,
  },
  fieldCoachName: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.subheadline,
    color: BrandColors.textPrimary,
  },
  fieldQuestion: {
    ...TextStyles.sectionHeadline,
    fontSize: 24,
    color: BrandColors.textPrimary,
    textAlign: 'center',
    marginBottom: 18,
    lineHeight: 34,
  },
  fieldSubtext: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.body,
    color: BrandColors.textSecondary,
    textAlign: 'center',
    marginBottom: 36,
    lineHeight: LineHeight.body,
    fontStyle: 'italic',
  },
  fieldInputContainer: {
    marginBottom: 36,
  },
  clarifyingAnswerInput: {
    minHeight: 130,
    textAlignVertical: 'top',
    paddingTop: 18,
  },
  progressIndicator: {
    alignItems: 'center',
    marginTop: 24,
  },
  progressText: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.bodySmall,
    color: BrandColors.textTertiary,
  },
  fieldNextButton: {
    backgroundColor: BrandColors.accent,
    paddingVertical: 18,
    paddingHorizontal: 36,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fieldNextButtonText: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  
  // Module styles
  moduleContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  moduleName: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.subheadline,
    color: BrandColors.textPrimary,
  },
  moduleCheckbox: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: BrandColors.inputBorder,
    backgroundColor: BrandColors.backgroundPrimary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  moduleCheckboxSelected: {
    borderColor: BrandColors.accent,
    backgroundColor: BrandColors.accent,
  },
  moduleCheckboxCheck: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.bodySmall,
  },
  moduleRadio: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: BrandColors.inputBorder,
    backgroundColor: BrandColors.backgroundPrimary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  moduleRadioSelected: {
    borderColor: BrandColors.accent,
  },
  moduleRadioDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: BrandColors.accent,
  },
  moduleTitle: {
    fontFamily: FontFamily.bodyMedium,
    fontSize: FontSize.meta,
    color: BrandColors.textTertiary,
    marginTop: 6,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  
  // Slider styles
  sliderContainer: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  sliderValue: {
    ...TextStyles.heroHeadline,
    color: BrandColors.accent,
    marginBottom: 28,
  },
  sliderWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 24,
  },
  slider: {
    flex: 1,
    height: 44,
    marginHorizontal: 18,
  },
  sliderLabel: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    color: BrandColors.textTertiary,
    minWidth: 24,
    textAlign: 'center',
  },
  sliderThumb: {
    backgroundColor: BrandColors.accent,
    width: 28,
    height: 28,
  },
  
  // Loading styles
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
  },
  loadingText: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.body,
    color: BrandColors.textSecondary,
    marginTop: 20,
    textAlign: 'center',
    lineHeight: 24,
  },
  revisionInput: {
    minHeight: 160,
    textAlignVertical: 'top',
    paddingTop: 18,
    borderColor: BrandColors.accent,
    borderWidth: 2,
  },
  
  // Multi-select styles
  multiSelectContainer: {
    maxHeight: 300,
  },
  multiSelectList: {
    paddingVertical: 10,
  },
  multiSelectOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 12,
    marginBottom: 10,
    backgroundColor: BrandColors.backgroundSecondary,
    borderWidth: 1,
    borderColor: BrandColors.cardBorder,
  },
  multiSelectOptionSelected: {
    backgroundColor: BrandColors.backgroundTertiary,
    borderColor: BrandColors.accent,
  },
  multiSelectOptionText: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.body,
    color: BrandColors.textPrimary,
    flex: 1,
  },
  multiSelectOptionTextSelected: {
    color: BrandColors.accent,
    fontFamily: FontFamily.bodyMedium,
  },
  checkmarkContainer: {
    marginLeft: 10,
  },
  checkmark: {
    color: BrandColors.accent,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
  },
  multiSelectCheckbox: {
    width: 28,
    height: 28,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: BrandColors.inputBorder,
    backgroundColor: BrandColors.backgroundPrimary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  multiSelectCheckboxSelected: {
    borderColor: BrandColors.accent,
    backgroundColor: BrandColors.accent,
  },
  multiSelectCheckmark: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodyBold,
    fontSize: FontSize.body,
  },
  multiSelectSelectionCount: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.bodySmall,
    color: BrandColors.textTertiary,
    textAlign: 'center',
    marginTop: 20,
    fontStyle: 'italic',
  },
  otherInputContainer: {
    marginTop: 24,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: BrandColors.divider,
  },
  otherInputLabel: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    color: BrandColors.textPrimary,
    marginBottom: 14,
  },
  otherInput: {
    borderWidth: 1,
    borderColor: BrandColors.accent,
    borderRadius: 14,
    padding: 18,
    fontSize: FontSize.body,
    fontFamily: FontFamily.bodyRegular,
    backgroundColor: BrandColors.inputBackground,
    color: BrandColors.textPrimary,
    minHeight: 54,
  },
  
  // Action plan styles
  actionPlanContainer: {
    flex: 1,
    paddingHorizontal: 24,
  },
  actionPlanTitle: {
    ...TextStyles.sectionHeadline,
    textAlign: 'center',
    marginBottom: 12,
    color: BrandColors.textPrimary,
  },
  actionPlanSubtitle: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.body,
    color: BrandColors.textSecondary,
    textAlign: 'center',
    marginBottom: 36,
    lineHeight: 24,
  },
  actionPlanList: {
    flex: 1,
    marginBottom: 24,
  },
  actionPlanStep: {
    backgroundColor: BrandColors.backgroundSecondary,
    borderRadius: 16,
    padding: 24,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: BrandColors.cardBorder,
  },
  actionPlanStepHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  actionPlanStepNumber: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: BrandColors.accent,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 18,
    flexShrink: 0,
  },
  actionPlanStepNumberText: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
  },
  actionPlanStepContent: {
    flex: 1,
  },
  actionPlanStepTitle: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.subheadline,
    color: BrandColors.textPrimary,
    marginBottom: 10,
    lineHeight: 26,
  },
  actionPlanPriorityBadge: {
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 14,
    alignSelf: 'flex-start',
  },
  actionPlanPriorityText: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.meta,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  actionPlanStepDescription: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.body,
    color: BrandColors.textSecondary,
    lineHeight: 24,
    marginLeft: 54,
  },
  actionPlanButtons: {
    flexDirection: 'row',
    paddingTop: 24,
    paddingBottom: 24,
    gap: 14,
  },
  revisePlanButton: {
    flex: 1,
    backgroundColor: BrandColors.backgroundSecondary,
    paddingVertical: 18,
    paddingHorizontal: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: BrandColors.cardBorder,
  },
  revisePlanButtonText: {
    color: BrandColors.textPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    textAlign: 'center',
  },
  acceptPlanButton: {
    flex: 1,
    backgroundColor: BrandColors.success,
    paddingVertical: 18,
    paddingHorizontal: 28,
    borderRadius: 14,
  },
  acceptPlanButtonText: {
    color: BrandColors.backgroundPrimary,
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.body,
    textAlign: 'center',
  },
  
  // Module intro styles
  moduleIntroContent: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  moduleIntroTitle: {
    ...TextStyles.sectionHeadline,
    textAlign: 'center',
    marginBottom: 28,
    color: BrandColors.textPrimary,
    lineHeight: 36,
  },
  moduleIntroNextSteps: {
    fontFamily: FontFamily.bodySemiBold,
    fontSize: FontSize.subheadline,
    textAlign: 'center',
    marginBottom: 24,
    color: BrandColors.accent,
    lineHeight: 30,
  },
  moduleIntroDescription: {
    fontFamily: FontFamily.bodyRegular,
    fontSize: FontSize.body,
    color: BrandColors.textSecondary,
    textAlign: 'center',
    lineHeight: LineHeight.body,
    paddingHorizontal: 12,
  },
});
